var namespace_empire___simulator =
[
    [ "Wyjatki", "namespace_empire___simulator_1_1_wyjatki.html", "namespace_empire___simulator_1_1_wyjatki" ],
    [ "AktualizacjaHandlarzy", "class_empire___simulator_1_1_aktualizacja_handlarzy.html", "class_empire___simulator_1_1_aktualizacja_handlarzy" ],
    [ "AktualizacjaOsad", "class_empire___simulator_1_1_aktualizacja_osad.html", "class_empire___simulator_1_1_aktualizacja_osad" ],
    [ "AktualizacjaStanuSwiata", "class_empire___simulator_1_1_aktualizacja_stanu_swiata.html", "class_empire___simulator_1_1_aktualizacja_stanu_swiata" ],
    [ "AktualizatorMapy", "class_empire___simulator_1_1_aktualizator_mapy.html", "class_empire___simulator_1_1_aktualizator_mapy" ],
    [ "FabrykaHandlarzy", "class_empire___simulator_1_1_fabryka_handlarzy.html", "class_empire___simulator_1_1_fabryka_handlarzy" ],
    [ "FabrykaOsad", "class_empire___simulator_1_1_fabryka_osad.html", "class_empire___simulator_1_1_fabryka_osad" ],
    [ "FabrykaZasobow", "class_empire___simulator_1_1_fabryka_zasobow.html", "class_empire___simulator_1_1_fabryka_zasobow" ],
    [ "GeneratorMapy", "class_empire___simulator_1_1_generator_mapy.html", "class_empire___simulator_1_1_generator_mapy" ],
    [ "GeneratorSwiata", "class_empire___simulator_1_1_generator_swiata.html", "class_empire___simulator_1_1_generator_swiata" ],
    [ "Handlarz", "class_empire___simulator_1_1_handlarz.html", "class_empire___simulator_1_1_handlarz" ],
    [ "IStrategiaAktualizacjiSwiata", "interface_empire___simulator_1_1_i_strategia_aktualizacji_swiata.html", "interface_empire___simulator_1_1_i_strategia_aktualizacji_swiata" ],
    [ "IStrategiaGenerowaniaSwiata", "interface_empire___simulator_1_1_i_strategia_generowania_swiata.html", "interface_empire___simulator_1_1_i_strategia_generowania_swiata" ],
    [ "IStrategiaHandlarza", "interface_empire___simulator_1_1_i_strategia_handlarza.html", "interface_empire___simulator_1_1_i_strategia_handlarza" ],
    [ "IStrategiaHandlu", "interface_empire___simulator_1_1_i_strategia_handlu.html", "interface_empire___simulator_1_1_i_strategia_handlu" ],
    [ "IStrategiaOsady", "interface_empire___simulator_1_1_i_strategia_osady.html", "interface_empire___simulator_1_1_i_strategia_osady" ],
    [ "LosowaniePotencjalu", "class_empire___simulator_1_1_losowanie_potencjalu.html", "class_empire___simulator_1_1_losowanie_potencjalu" ],
    [ "LosowanieZasobu", "class_empire___simulator_1_1_losowanie_zasobu.html", "class_empire___simulator_1_1_losowanie_zasobu" ],
    [ "Magazyn", "class_empire___simulator_1_1_magazyn.html", "class_empire___simulator_1_1_magazyn" ],
    [ "OknoGry", "class_empire___simulator_1_1_okno_gry.html", "class_empire___simulator_1_1_okno_gry" ],
    [ "Osada", "class_empire___simulator_1_1_osada.html", "class_empire___simulator_1_1_osada" ],
    [ "PodstawowaStrategiaAktualizacjiSwiata", "class_empire___simulator_1_1_podstawowa_strategia_aktualizacji_swiata.html", "class_empire___simulator_1_1_podstawowa_strategia_aktualizacji_swiata" ],
    [ "PodstawowaStrategiaGenerowaniaSwiata", "class_empire___simulator_1_1_podstawowa_strategia_generowania_swiata.html", "class_empire___simulator_1_1_podstawowa_strategia_generowania_swiata" ],
    [ "PodstawowaStrategiaHandlarza", "class_empire___simulator_1_1_podstawowa_strategia_handlarza.html", "class_empire___simulator_1_1_podstawowa_strategia_handlarza" ],
    [ "PodstawowaStrategiaHandlu", "class_empire___simulator_1_1_podstawowa_strategia_handlu.html", "class_empire___simulator_1_1_podstawowa_strategia_handlu" ],
    [ "PodstawowaStrategiaOsady", "class_empire___simulator_1_1_podstawowa_strategia_osady.html", "class_empire___simulator_1_1_podstawowa_strategia_osady" ],
    [ "Populacja", "class_empire___simulator_1_1_populacja.html", "class_empire___simulator_1_1_populacja" ],
    [ "PotencjalWydobywczy", "class_empire___simulator_1_1_potencjal_wydobywczy.html", "class_empire___simulator_1_1_potencjal_wydobywczy" ],
    [ "Swiat", "class_empire___simulator_1_1_swiat.html", "class_empire___simulator_1_1_swiat" ],
    [ "Targ", "class_empire___simulator_1_1_targ.html", "class_empire___simulator_1_1_targ" ],
    [ "Test", "class_empire___simulator_1_1_test.html", null ],
    [ "TextBoxLabel", "class_empire___simulator_1_1_text_box_label.html", "class_empire___simulator_1_1_text_box_label" ],
    [ "WozHandlarza", "class_empire___simulator_1_1_woz_handlarza.html", "class_empire___simulator_1_1_woz_handlarza" ],
    [ "Zasob", "class_empire___simulator_1_1_zasob.html", "class_empire___simulator_1_1_zasob" ]
];